### ISSUE TITLE
提议：将第13届OSDT大会提前到2021年7-8月份召开

### ISSUE THREAD

**Issue by lazyparser** [hellogcc/wg#4]
## 时间

从2009年开始举办的一年一届的 OSDT Conf （原 HelloGCC Workshop），时间上一般集中在第四季度。

最近几年从10月份变成了11月份，今年变成了12月份。

在第四季度的问题在于：
- 冬天，出差来现场可能会比夏天多一些不方便。
- 年底社区的小伙伴赶进度的比较多，会议也比较多，容易冲突。例如本次12月5日同时有深圳的C++大会和其他几个会议同一天举办。
- 对于学生而言是临近考试季节。

因此提出，将OSDT2021定为7-8月份举办。

## 地点

在地点选择上，过去11届地点都在北京，第12届由于疫情改成了线上。第13届默认在北京，但是有可能变更为上海或其他城市？

**Comment by shining1984** [comment]
地点投杭州一票。
时间7、8月份都好。

**Comment by lazyparser** [comment]
显而易见，我们已经拖延过了8月😂
